# Generated by Django 2.1.4 on 2018-12-31 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djtest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flag',
            name='seq',
            field=models.IntegerField(),
        ),
    ]
